// <auto-generated />
namespace LegacyGT.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddDonationToSponsor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDonationToSponsor));
        
        string IMigrationMetadata.Id
        {
            get { return "202105031543169_AddDonationToSponsor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
